name: Build

on:
  push:
    branches: []
  pull_request:
    branches: []

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    name: All

    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - x86_64-apple-darwin
        - x86_64-pc-windows-msvc
        include:
        - target: x86_64-unknown-linux-gnu
          os:     ubuntu-latest
        - target: x86_64-apple-darwin
          os:     macos-latest
        - target: x86_64-pc-windows-msvc
          os:     windows-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: "-D warnings"

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        components: clippy

    - name: Info
      run: |
        rustup --version
        cargo --version
        cargo clippy --version

    - name: Build
      run: |
        cargo build --target ${{ matrix.target }}
        cargo build --release --target ${{ matrix.target }}

    - name: Clippy
      run: |
        cargo clippy --release --features accuraterip,cddb,ctdb,musicbrainz,serde --target ${{ matrix.target }}
        cargo clippy --release --no-default-features --target ${{ matrix.target }}
        cargo clippy --release --no-default-features --features accuraterip --target ${{ matrix.target }}
        cargo clippy --release --no-default-features --features cddb --target ${{ matrix.target }}
        cargo clippy --release --no-default-features --features ctdb --target ${{ matrix.target }}
        cargo clippy --release --no-default-features --features musicbrainz --target ${{ matrix.target }}
        cargo clippy --release --no-default-features --features serde --target ${{ matrix.target }}

    - name: Tests (Debug)
      run: |
        cargo test --features accuraterip,cddb,ctdb,musicbrainz,serde --target ${{ matrix.target }}
        cargo test --no-default-features --target ${{ matrix.target }}
        cargo test --no-default-features --features accuraterip --target ${{ matrix.target }}
        cargo test --no-default-features --features cddb --target ${{ matrix.target }}
        cargo test --no-default-features --features ctdb --target ${{ matrix.target }}
        cargo test --no-default-features --features musicbrainz --target ${{ matrix.target }}
        cargo test --no-default-features --features serde --target ${{ matrix.target }}

    - name: Tests (Release)
      run: |
        cargo test --release --features accuraterip,cddb,ctdb,musicbrainz,serde --target ${{ matrix.target }}
        cargo test --release --no-default-features --target ${{ matrix.target }}
        cargo test --release --no-default-features --features accuraterip --target ${{ matrix.target }}
        cargo test --release --no-default-features --features cddb --target ${{ matrix.target }}
        cargo test --release --no-default-features --features ctdb --target ${{ matrix.target }}
        cargo test --release --no-default-features --features musicbrainz --target ${{ matrix.target }}
        cargo test --release --no-default-features --features serde --target ${{ matrix.target }}
